#!/bin/bash

## Get the fetch info 
user="${USER}"
shell="$(basename ${SHELL})"
wm="$(xprop -id $(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}') -notype -f _NET_WM_NAME 8t | grep "WM_NAME" | cut -f2 -d \")"
resolution="$(xwininfo -root | grep geometry | awk '{print $2}' | cut -d + -f1)"
kernel="$(uname -r | cut -d '-' -f1)"

# Print out the actual fetch

printf '%b' "
welcome, ${user}
  ／l、        • ${wm}
（ﾟ､ ｡ ７      • ${shell}
 l、ﾞ ~ヽ      • ${resolution}
  じしf_, )ノ  • ${kernel}
"