#!/bin/sh

# sourced at boot by ~/.xinitrc and most display managers

export XDG_CONFIG_HOME="$HOME/.config"
export PATH="$HOME/.local/bin:$PATH"


nm-applet &
volumeicon &
xfce4-power-manager &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11 &
xscreensaver -no-splash &

xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 27 &

xrandr --output DisplayPort-0 --primary --mode 2560x1440 -r 144 --pos 1920x0 --rotate normal --set TearFree on --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --pos 0x360 --rotate normal -r 59 --set TearFree on &

xrdb -merge ~/.Xresources &
xrdb ~/.Xresources &
